version: "2"
services:
  postgres:
    image: postgres:9.5.3
    volumes:
       - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
